[project]
name = "endstone-customalert"
version = "0.1.0"
authors = [
    {name = "ClickedTran", email = "clickedwp@gmail.com"},
]
dependencies = ["endstone>=0.11.3"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.entry-points."endstone"]
customalert = "customalert.main:CustomAlert"